### ISSUE TITLE
index out of range after removing entities from world

### ISSUE THREAD

**Issue by dfirebaugh** [yohamta/donburi#2]
I'm having an issue removing entities from the world.

I have a lifespan system that removes entities when they are "end of life".
https://github.com/dfirebaugh/cheezewiz/blob/main/examples/choppa/internal/system/lifespan.go#L22-L41

However, when I go to spawn more, i get an index out of range error:
```
panic: runtime error: index out of range [5] with length 5

goroutine 14 [running]:
github.com/yohamta/donburi/internal/storage.(*SimpleStorage).Component(...)
        C:/Users/dfire/go/pkg/mod/github.com/yohamta/donburi@v0.0.6/internal/storage/storage.go:37
github.com/yohamta/donburi.(*Entry).Component(...)
        C:/Users/dfire/go/pkg/mod/github.com/yohamta/donburi@v0.0.6/entry.go:33
cheezewiz/examples/choppa/internal/entity.MakeProjectile({0x5b3e98, 0xc00012c700}, 0xc000010f90)
        C:/build/cheezewiz/examples/choppa/internal/entity/projectile.go:15 +0x5a5
cheezewiz/examples/choppa/internal/system.Player.Update.func1(0xc00055a280?)
        C:/build/cheezewiz/examples/choppa/internal/system/player.go:54 +0xf3
github.com/yohamta/donburi/query.(*Query).EachEntity.func1(0xc000004498?)
        C:/Users/dfire/go/pkg/mod/github.com/yohamta/donburi@v0.0.6/query/query.go:42 +0x3b
github.com/yohamta/donburi/query.(*Query).EachEntity(0xc0000c7c90?, {0x5b3e98, 0xc00012c700}, 0xc0000c7b80)
        C:/Users/dfire/go/pkg/mod/github.com/yohamta/donburi@v0.0.6/query/query.go:47 +0x239
cheezewiz/examples/choppa/internal/system.Player.Update({0x4?}, {0x5b3e98?, 0xc00012c700?})
        C:/build/cheezewiz/examples/choppa/internal/system/player.go:26 +0x4d
cheezewiz/examples/choppa/internal/mediator.Mediator.Update(...)
        C:/build/cheezewiz/examples/choppa/internal/mediator/mediator.go:45
cheezewiz/pkg/ebitenwrapper.(*Game).Update(0x0?)
        C:/build/cheezewiz/pkg/ebitenwrapper/ebitenwrapper.go:27 +0x22
github.com/hajimehoshi/ebiten/v2.(*imageDumper).update(0xc00057e190)
        C:/Users/dfire/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/imagedumper_desktop.go:111 +0x52
github.com/hajimehoshi/ebiten/v2.(*imageDumperGame).Update(0xc0000c7db8?)
        C:/Users/dfire/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/run.go:146 +0x7d
github.com/hajimehoshi/ebiten/v2.(*gameForUI).Update(0x5b45a0?)
        C:/Users/dfire/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/gameforui.go:46 +0x22
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrameImpl(0xc000068640, {0x5b45a0, 0x81dac0}, 0x1, 0x4090000000000000, 0x4090000000000000, 0xc0000c7e98?)
        C:/Users/dfire/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/ui/context.go:116 +0x157
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrame(0xc000004630?, {0x5b45a0, 0x81dac0}, 0xc00006e238?, 0xc00041e820?, 0xc00041e8a8?)
        C:/Users/dfire/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/ui/context.go:64 +0x8e
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loop(0x81d8c0)
        C:/Users/dfire/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/ui/ui_glfw.go:1065 +0x1ea
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run.func1()
        C:/Users/dfire/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/ui/run_notsinglethread.go:46 +0x13d
created by github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run
        C:/Users/dfire/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/ui/run_notsinglethread.go:33 +0x20a
exit status 2```

**Comment by yohamta** [comment]
@dfirebaugh  Hi, I have fixed the problem at v0.0.7, and I have also tagged the version number as v1.0.0 since it has all the necessary features. So, Please use v1.0.0. Thank you for finding the issue!

**Comment by yohamta** [comment]
@dfirebaugh Then the samples of the games you're creating are great! Keep up the good work 👍

**Comment by dfirebaugh** [comment]
@yohamta  Thanks!

I'm doing a makeshift gamejam this weekend with some friends.  I'm also planning on using your ganim8 library.

thanks so much for making these awesome libraries!

**Comment by yohamta** [comment]
Thank you for using my libraries! Have fun! :)
